{
 "title": "API Server Metrics",
 "tags": [ "aeris" ],
 "time": { "from": "now-18d", "to": "now-4d" },
 "templating": {
  "list": [
   { "name": "DATASOURCE", "label": "Datasource", "query": "prometheus" },
   {
    "name": "grpc_method",
    "label": "GRPC Method",
    "query": {
     "query": "label_values(grpc_server_handled_total{app_kubernetes_io_name=\"apiserver\",app_kubernetes_io_part_of=\"aeris\"}, grpc_method)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Hbase", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hbase average load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "hbase_master_server_averageload"
    }
   ]
  },
  {
   "title": "Hbase average load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "hbase_master_server_averageload"
    }
   ]
  },
  {
   "title": "Hbase regionserver number of requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "irate(hbase_regionserver_server_totalrequestcount[5m])"
    }
   ]
  },
  {
   "title": "Hbase master server cluster requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(hbase_master_server_clusterrequests[5m])"
    }
   ]
  },
  {
   "title": "WAL Rolls per 5m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(hbase_regionserver_wal_rollrequest[5m])"
    }
   ]
  },
  {
   "title": "Scan count per 5m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(irate(hbase_scancount[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Regionserver time spent in GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"core\"}[5m]))"
    }
   ]
  },
  {
   "title": "Get count per 5m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(irate(hbase_getcount[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "region server callqueuetoobig rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(hbase_regionserver_ipc_exceptions_callqueuetoobig[2m])"
    }
   ]
  },
  {
   "title": "Put count per 5m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum(irate(hbase_putcount[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Region server num open connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hbase_regionserver_ipc_numopenconnections"
    }
   ]
  },
  {
   "title": "Hbase compaction completed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "irate(hbase_compactionscompletedcount[5m])"
    }
   ]
  },
  {
   "title": "Node Netstat TCP ListenOverflows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_ListenOverflows[5m])"
    },
    {
     "expr": "irate(node_netstat_TcpExt_ListenDrops[5m])"
    }
   ]
  },
  {
   "title": "Core CPU Use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"core\"}[5m])"
    }
   ]
  },
  {
   "title": "Node Netstat TCP Active Opens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens[5m])"
    }
   ]
  },
  {
   "title": "Blockcache Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "hbase_regionserver_server_blockcachesize"
    }
   ]
  },
  {
   "title": "Storage Latency Histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(storage_latency_histogram_bucket{app=\"ingest\"}[5m]))"
    }
   ]
  },
  {
   "title": "CPU Usage Overall",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (100*(avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m]))))"
    }
   ]
  },
  {
   "title": "Blockcache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "hbase_regionserver_server_blockcachehitcount/(hbase_regionserver_server_blockcachemisscount+hbase_regionserver_server_blockcachehitcount)"
    }
   ]
  },
  {
   "title": "Node Network Receive Bytes Total 2m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total[2m])"
    }
   ]
  },
  {
   "title": "Memstore Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(hbase_memstoresize) by (instance)"
    }
   ]
  },
  {
   "title": "Node Netstat TCP InErrs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(node_netstat_Tcp_InErrs[5m])"
    }
   ]
  },
  {
   "title": "Get Count Per 5m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(sum(rate(hbase_getcount[5m])))"
    }
   ]
  },
  {
   "title": "Gets/s by app",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sort_desc(sum by (grpc_method, app) (irate(grpc_client_handled_total{grpc_service=\"RouterV1\", grpc_method=\"Get\"}[2m])) != 0)"
    }
   ]
  },
  { "title": "GRPC Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "# GRPC Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aeris_apiserver_grpc_num_client_connections{app=\"apiserver\", state=\"READY\"})-sum(aeris_apiserver_grpc_num_client_connections{app=\"apiserver\", state=\"SHUTDOWN\"})",
     "legendFormat": "# GRPC connections"
    }
   ]
  },
  {
   "title": "# Active GRPC Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 3, "y": 106 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aeris_apiserver_grpc_num_client_connections{app=\"apiserver\", state=\"READY\"} - on (kubernetes_pod_name) aeris_apiserver_grpc_num_client_connections{app=\"apiserver\", state=\"SHUTDOWN\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "# New GRPC Connection (5m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 106 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(aeris_apiserver_grpc_num_client_connections{app=\"apiserver\", state=\"READY\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Subscriptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 } },
  {
   "title": "Notifications Sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(notifications_sent_total[5m])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Batches Sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(notifications_batches_sent_total[5m])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Live Subscriptions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "subscriptions_added_total - subscriptions_removed_total",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Notifications Looked Up",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(notifications_looked_up_total[5m])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "% Notifications Hitting Auth Cache",
   "type": "graph",
   "description": "This is the percentage of notifications that hit the cach versus the total number of notifications sent.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 129 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(notifications_auth_cached{app_kubernetes_io_name=\"apiserver\",app_kubernetes_io_part_of=\"aeris\"}[5m])/irate(notifications_sent_total{app_kubernetes_io_name=\"apiserver\",app_kubernetes_io_part_of=\"aeris\"}[5m])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Subscription Notifications Skipped",
   "type": "graph",
   "description": "This is the total number of subscription notifications that we dropped because there it did not have permissions on the associated dataset.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(notifications_skipped_total{app_kubernetes_io_name=\"apiserver\",app_kubernetes_io_part_of=\"aeris\"}[5m])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Kafka queues lag",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 143 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kafka_log_logendoffset) by (partition, topic) - on (partition, topic) max(offset_consumed{app_kubernetes_io_name=\"apiserver\",app_kubernetes_io_part_of=\"aeris\"}) by (partition, topic)",
     "legendFormat": "{{topic}} {{partition}}"
    }
   ]
  },
  {
   "title": "Get request to first response latency",
   "type": "graph",
   "description": "Latency from request to the first batch response of get requests across all apiservers",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 152 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(aeris_apiserver_get_first_response_latency_seconds_bucket[5m])) by (le)) * 1e3",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(aeris_apiserver_get_first_response_latency_seconds_bucket[5m])) by (le))  * 1e3",
     "legendFormat": "50th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(aeris_apiserver_get_first_response_latency_seconds_bucket[5m])) by (le))  * 1e3",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "Rate of gets received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 161 },
   "targets": [
    {
     "expr": "rate(aeris_apiserver_gets_received_total[5m])",
     "legendFormat": "{{kubernetes_pod_name}} {{type}}"
    }
   ]
  },
  {
   "title": "Get range window size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(aeris_apiserver_get_range_window_size_seconds_bucket[5m])) by (le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(aeris_apiserver_get_range_window_size_seconds_bucket[5m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(aeris_apiserver_get_range_window_size_seconds_bucket[5m])) by (le))",
     "legendFormat": "50th"
    }
   ]
  },
  { "title": "GRPC Calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 169 } },
  {
   "title": "# grpc successful publish requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 170 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{grpc_method=\"Publish\", grpc_code=\"OK\"}[5m])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "# grpc error publish requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 170 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{grpc_method=\"Publish\", grpc_code!=\"OK\"}[5m]) > 0",
     "legendFormat": "{{ kubernetes_pod_name }} / {{ grpc_code }}"
    }
   ]
  },
  {
   "title": "# grpc successful $grpc_method requests (based on GRPC method)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 178 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{grpc_method=\"$grpc_method\", grpc_code=\"OK\"}[5m]) > 0",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "# grpc error $grpc_method requests (based on GRPC method)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 178 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{grpc_method=\"$grpc_method\", grpc_code!=\"OK\"}[5m]) > 0",
     "legendFormat": "{{ kubernetes_pod_name }} / {{ grpc_code }}"
    }
   ]
  },
  { "title": "Process CPU/Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 186 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 187 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total[5m])"
    }
   ]
  },
  {
   "title": "Heap usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 187 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{kubernetes_pod_name=~\"apiserver.*\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  { "title": "Spanner", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 194 } },
  {
   "title": "Spanner dataset creation errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 195 },
   "targets": [
    {
     "expr": "rate(spanner_ds_creation_error{app=\"apiserver\", app_kubernetes_io_part_of=\"aeris\"}[5m])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Spanner dataset creation failed precondition error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 195 },
   "targets": [
    {
     "expr": "rate(spanner_ds_creation_failed_precondition_error{app_kubernetes_io_name=\"apiserver\", app_kubernetes_io_part_of=\"aeris\"}[5m])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  }
 ]
}