{
 "title": "On-Prem Troubleshooting",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Node Instance",
    "query": {
     "query": "container_memory_working_set_bytes"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "container_memory_working_set_bytes"
    }
   },
   { "name": "topk", "label": "Topk", "query": "5,10,15,20,30,50" }
  ]
 },
 "panels": [
  {
   "title": "Cluster Scale",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Active Devices",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(turbine_devices_software{status=\"active\"})"
      }
     ]
    },
    {
     "title": "Active Interfaces",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(turbine_shards_total{id=~\"aggregate-counter-rate-1m\"})"
      }
     ]
    },
    {
     "title": "IPFIX Notification Received Rate",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
     "targets": [
      {
       "expr": "sum(rate(clover_ingest_num_notifications_received{type=\"ipfix\"}[5m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Count",
     "type": "stat",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (instance) (\n    label_replace(node_cpu_seconds_total{mode=\"idle\"}, \"instance\", \"$1\", \"instance\", \"(.*):.*\")\n  )",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Top CPU Processes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "topk($topk, avg by (instance, app) (rate(process_cpu_seconds_total[5m])))"
      }
     ]
    },
    {
     "title": "I/O Wait Avg by Node",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "label_replace(avg by (instance) (irate(node_cpu_seconds_total{mode=\"iowait\"}[5m])), \"instance\", \"$1\", \"instance\", \"(.*):.*\")"
      }
     ]
    },
    {
     "title": "CPU Use Avg by Node",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "label_replace( 1 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m]))), \"instance\", \"$1\", \"instance\", \"(.*):.*\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Available Memory",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node Available Memory Over Time",
     "type": "timeseries",
     "description": "An estimate of how much memory is available for starting new applications, without swapping. Calculated from MemFree, SReclaimable, the size of the file LRU lists, and the low watermarks in each zone. The estimate takes into account that the system needs some page cache to function well, and that not all reclaimable slab will be reclaimable, due to items being in use. The impact of those factors will vary from system to system.",
     "gridPos": { "h": 8, "w": 10, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "OOM Kills",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
     "targets": [
      { "expr": "node_vmstat_oom_kill", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Total Memory",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "node_memory_MemTotal_bytes", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Top Memory RSS (container)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk($topk, container_memory_rss{instance=~\"$instance\",container=~\"$container\"})",
       "legendFormat": "{{instance}} {{container}}"
      }
     ]
    },
    {
     "title": "Top Memory RSS (sum by container)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk($topk, sum by (container) (container_memory_rss{instance=~\"$instance\",container=~\"$container\"}))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Top Memory Working Set (container)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk($topk, container_memory_working_set_bytes{instance=~\"$instance\",container=~\"$container\"})",
       "legendFormat": "{{instance}} {{container}} {{pod}}"
      }
     ]
    },
    {
     "title": "Top Memory Working Set (sum by container)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk($topk, sum by (container) (container_memory_working_set_bytes{instance=~\"$instance\",container=~\"$container\"}))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filesystem Sizes",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{mountpoint=~\"/|/data\"}",
       "legendFormat": "{{instance}} {{device}} --> {{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk Usage of /",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - ((node_filesystem_avail_bytes{mountpoint=~\"/\"}) / node_filesystem_size_bytes{mountpoint=~\"/\"})"
      }
     ]
    },
    {
     "title": "Disk Usage of /data",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - ((node_filesystem_avail_bytes{mountpoint=~\"/data\"}) / node_filesystem_size_bytes{mountpoint=~\"/data\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Overview",
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 31 },
     "options": {
      "content": "[Interpreting Prometheus metrics for Linux disk I/O utilization](https://brian-candler.medium.com/interpreting-prometheus-metrics-for-linux-disk-i-o-utilization-4db53dfedcfc)"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Writes per Second (w/s)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "rate(node_disk_writes_completed_total[5m])"
      }
     ]
    },
    {
     "title": "Reads per Second (r/s)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 33 },
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total[5m])"
      }
     ]
    },
    {
     "title": "Wriiten Bytes per Second (wkB/s)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(node_disk_written_bytes_total[5m])"
      }
     ]
    },
    {
     "title": "Read Bytes per Second (rkB/s)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total[5m])"
      }
     ]
    },
    {
     "title": "Write Service Time Avg (w_await)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(node_disk_write_time_seconds_total[5m])/rate(node_disk_writes_completed_total[5m])"
      }
     ]
    },
    {
     "title": "Read Service Time Avg (r_await)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(node_disk_read_time_seconds_total[5m])/rate(node_disk_reads_completed_total[5m])"
      }
     ]
    },
    {
     "title": "Avg Queue Depth (aqu-sz)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "rate(node_disk_io_time_weighted_seconds_total[5m])"
      }
     ]
    },
    {
     "title": "Disk Flush Duration",
     "type": "timeseries",
     "description": "This metric is not available in older Linux kernels",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(node_disk_flush_requests_time_seconds_total[5m])/rate(node_disk_flush_requests_total[5m])"
      }
     ]
    }
   ]
  },
  {
   "title": "HBase",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Master Active Time",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 11, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "targets": [
      {
       "expr": "hbase_master_server_masteractivetime"
      },
      { "expr": "hbaseregionserver" }
     ]
    },
    {
     "title": "Region Servers (Live and Dead)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 13, "x": 11, "y": 32 },
     "targets": [
      {
       "expr": "hbase_master_server_numregionservers != 0"
      },
      {
       "expr": "hbase_master_server_numdeadregionservers != 0"
      }
     ]
    },
    {
     "title": "Regions (Hosted and In-Transition)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "hbase_regionserver_server_regioncount != 0"
      },
      {
       "expr": "hbase_master_assignmentmanager_ritcount != 0"
      }
     ]
    },
    {
     "title": "RPC Open Connections",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 13, "x": 11, "y": 37 },
     "targets": [
      {
       "expr": "hbase_regionserver_ipc_numopenconnections"
      },
      {
       "expr": "hbase_master_assignmentmanager_ritcount != 0"
      }
     ]
    },
    {
     "title": "Exceptions",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "rate(hbase_master_ipc_exceptions[5m]) != 0",
       "legendFormat": "hbase_master_ipc_exceptions {{instance}}"
      },
      {
       "expr": "rate(hbase_master_ipc_exceptions_callqueuetoobig[5m]) != 0",
       "legendFormat": "hbase_master_ipc_exceptions_callqueuetoobig {{instance}}"
      },
      {
       "expr": "rate(hbase_master_ipc_exceptions_failedsanitycheckexception[5m]) != 0",
       "legendFormat": "hbase_master_ipc_exceptions_failedsanitycheckexception {{instance}}"
      },
      {
       "expr": "rate(hbase_master_ipc_exceptions_multiresponsetoolarge[5m]) != 0",
       "legendFormat": "hbase_master_ipc_exceptions_multiresponsetoolarge {{instance}}"
      },
      {
       "expr": "rate(hbase_master_ipc_exceptions_notservingregionexception[5m]) != 0",
       "legendFormat": "hbase_master_ipc_exceptions_notservingregionexception {{instance}}"
      },
      {
       "expr": "rate(hbase_master_ipc_exceptions_notservingregionexception[5m]) != 0",
       "legendFormat": "hbase_master_ipc_exceptions_notservingregionexception {{instance}}"
      },
      {
       "expr": "rate(hbase_master_ipc_exceptions_regionmovedexception[5m]) != 0",
       "legendFormat": "hbase_master_ipc_exceptions_regionmovedexception {{instance}}"
      },
      {
       "expr": "rate(hbase_master_ipc_exceptions_regiontoobusyexception[5m]) != 0",
       "legendFormat": "hbase_master_ipc_exceptions_regiontoobusyexception {{instance}}"
      },
      {
       "expr": "rate(hbase_master_ipc_exceptions_scannerresetexception[5m]) != 0",
       "legendFormat": "hbase_master_ipc_exceptions_scannerresetexception {{instance}}"
      },
      {
       "expr": "rate(hbase_master_ipc_exceptions_unknownscannerexception[5m]) != 0",
       "legendFormat": "hbase_master_ipc_exceptions_unknownscannerexception {{instance}}"
      },
      {
       "expr": "rate(hbase_regionserver_ipc_exceptions[5m]) != 0",
       "legendFormat": "hbase_regionserver_ipc_exceptions {{instance}}"
      },
      {
       "expr": "rate(hbase_regionserver_ipc_exceptions_callqueuetoobig[5m]) != 0",
       "legendFormat": "hbase_regionserver_ipc_exceptions_callqueuetoobig {{instance}}"
      },
      {
       "expr": "rate(hbase_regionserver_ipc_exceptions_failedsanitycheckexception[5m]) != 0",
       "legendFormat": "hbase_regionserver_ipc_exceptions_failedsanitycheckexception {{instance}}"
      },
      {
       "expr": "rate(hbase_regionserver_ipc_exceptions_multiresponsetoolarge[5m]) != 0",
       "legendFormat": "hbase_regionserver_ipc_exceptions_multiresponsetoolarge {{instance}}"
      },
      {
       "expr": "rate(hbase_regionserver_ipc_exceptions_notservingregionexception[5m]) != 0",
       "legendFormat": "hbase_regionserver_ipc_exceptions_notservingregionexception {{instance}}"
      },
      {
       "expr": "rate(hbase_regionserver_ipc_exceptions_outoforderscannernextexception[5m]) != 0",
       "legendFormat": "hbase_regionserver_ipc_exceptions_outoforderscannernextexception {{instance}}"
      },
      {
       "expr": "rate(hbase_regionserver_ipc_exceptions_regionmovedexception[5m]) != 0",
       "legendFormat": "hbase_regionserver_ipc_exceptions_regionmovedexception {{instance}}"
      },
      {
       "expr": "rate(hbase_regionserver_ipc_exceptions_regiontoobusyexception[5m]) != 0",
       "legendFormat": "hbase_regionserver_ipc_exceptions_regiontoobusyexception {{instance}}"
      },
      {
       "expr": "rate(hbase_regionserver_ipc_exceptions_scannerresetexception[5m]) != 0",
       "legendFormat": "hbase_regionserver_ipc_exceptions_scannerresetexception {{instance}}"
      },
      {
       "expr": "rate(hbase_regionserver_ipc_exceptions_unknownscannerexception[5m]) != 0",
       "legendFormat": "hbase_regionserver_ipc_exceptions_unknownscannerexception {{instance}}"
      }
     ]
    },
    {
     "title": "Server Total Request Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 13, "x": 11, "y": 43 },
     "targets": [
      {
       "expr": "rate(hbase_regionserver_server_totalrequestcount[5m])"
      }
     ]
    },
    {
     "title": "Num Calls in Queues",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "hbase_regionserver_ipc_numcallsingeneralqueue != 0"
      },
      {
       "expr": "hbase_regionserver_ipc_numcallsinmetapriorityqueue != 0"
      },
      {
       "expr": "hbase_regionserver_ipc_numcallsinpriorityqueue != 0"
      },
      {
       "expr": "hbase_regionserver_ipc_numcallsinreadqueue != 0"
      },
      {
       "expr": "hbase_regionserver_ipc_numcallsinreplicationqueue != 0"
      },
      {
       "expr": "hbase_regionserver_ipc_numcallsinscanqueue != 0"
      },
      {
       "expr": "hbase_regionserver_ipc_numcallsinwritequeue != 0"
      },
      {
       "expr": "hbase_master_ipc_numcallsingeneralqueue != 0"
      },
      {
       "expr": "hbase_master_ipc_numcallsinmetapriorityqueue != 0"
      },
      {
       "expr": "hbase_master_ipc_numcallsinpriorityqueue != 0"
      },
      {
       "expr": "hbase_master_ipc_numcallsinreadqueue != 0"
      },
      {
       "expr": "hbase_master_ipc_numcallsinreplicationqueue != 0"
      },
      {
       "expr": "hbase_master_ipc_numcallsinscanqueue != 0"
      },
      {
       "expr": "hbase_master_ipc_numcallsinwritequeue != 0"
      }
     ]
    },
    {
     "title": "Server Write Request Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 13, "x": 11, "y": 49 },
     "targets": [
      {
       "expr": "rate(hbase_regionserver_server_writerequestcount[5m])"
      }
     ]
    },
    {
     "title": "Regionserver Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "hbase_regionserver_server_flushqueuelength != 0"
      },
      {
       "expr": "hbase_regionserver_server_splitqueuelength != 0"
      },
      {
       "expr": "hbase_regionserver_server_compactionqueuelength != 0"
      },
      {
       "expr": "hbase_regionserver_server_largecompactionqueuelength != 0"
      },
      {
       "expr": "hbase_regionserver_server_smallcompactionqueuelength != 0"
      }
     ]
    },
    {
     "title": "Server Read Request Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 13, "x": 11, "y": 55 },
     "targets": [
      {
       "expr": "rate(hbase_regionserver_server_readrequestcount[5m])"
      }
     ]
    },
    {
     "title": "Compactions",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "sum by (instance) (rate(hbase_compactionscompletedcount[5m])) != 0",
       "legendFormat": "hbase_compactionscompletedcount rate {{instance}}"
      },
      {
       "expr": "sum by (instance) (rate(hbase_compactionsqueuedcount[5m])) != 0",
       "legendFormat": "hbase_compactionsqueuedcount rate {{instance}}"
      },
      {
       "expr": "sum by (instance) (rate(hbase_compactionsfailedcount[5m])) != 0",
       "legendFormat": "hbase_compactionsfailedcount rate {{instance)"
      }
     ]
    }
   ]
  },
  {
   "title": "Hadoop",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Live, Stale and Dead DataNodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "hadoop_namenode_numlivedatanodes != 0"
      },
      {
       "expr": "hadoop_namenode_numstaledatanodes != 0"
      },
      {
       "expr": "hadoop_namenode_numdeaddatanodes != 0"
      }
     ]
    },
    {
     "title": "Missing and Corrupt Blocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 33 },
     "targets": [
      {
       "expr": "hadoop_namenode_missingblocks != 0"
      },
      {
       "expr": "hadoop_namenode_corruptblocks != 0"
      }
     ]
    },
    {
     "title": "Log Warning and Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "rate(hadoop_namenode_logerror[5m]) != 0",
       "legendFormat": "hadoop_namenode_logerror {{instance}} "
      },
      {
       "expr": "rate(hadoop_namenode_logwarn[5m]) != 0",
       "legendFormat": "hadoop_namenode_logwarn {{instance}}"
      },
      {
       "expr": "rate(hadoop_journalnode_logerror[5m]) != 0",
       "legendFormat": "hadoop_journalnode_logerror {{instance}} "
      },
      {
       "expr": "rate(hadoop_journalnode_logwarn[5m]) != 0",
       "legendFormat": "hadoop_journalnode_logwarn {{instance}}"
      },
      {
       "expr": "rate(hadoop_datanode_logerror[5m]) != 0",
       "legendFormat": "hadoop_datanode_logerror {{instance}} "
      },
      {
       "expr": "rate(hadoop_datanode_logwarn[5m]) != 0",
       "legendFormat": "hadoop_datanode_logwarn {{instance}}"
      }
     ]
    },
    {
     "title": "Datanode Network & File I/O Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 41 },
     "targets": [
      {
       "expr": "rate(hadoop_datanode_datanodenetworkerrors[5m])",
       "legendFormat": "hadoop_datanode_datanodenetworkerrors {{instance}}"
      },
      {
       "expr": "rate(hadoop_datanode_totalfileioerrors[5m])",
       "legendFormat": "hadoop_datanode_totalfileioerrors {{instance}}"
      }
     ]
    },
    {
     "title": "Datanode Fsync Avg Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "hadoop_datanode_fsyncnanosavgtime"
      }
     ]
    }
   ]
  },
  {
   "title": "Aeris Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Aeris Storage Driver Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(aeris_storage_hbase_errors_total[5m])"
      }
     ]
    },
    {
     "title": "JVM Avg GC Duration",
     "type": "timeseries",
     "description": "NOTE: this does not necessarily correlate with the JVM pauses logged by the processes",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(sum without(gc) (rate(jvm_gc_collection_seconds_sum[2m]))) / (sum without(gc) (rate(jvm_gc_collection_seconds_count[2m])))"
      }
     ]
    },
    {
     "title": "PostDB Kafka Lag",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(kafka_log_log_value{topic=\"postDB_v2\", name=\"LogEndOffset\"}) by (partition, topic) - max(offset_consumed{topic=\"postDB_v2\"}) by (topic, partition)"
      }
     ]
    },
    {
     "title": "JVM % of Time Spent in GC",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"core\"}[2m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Aeris Writes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Ingest \"Store\" Duration",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "sum(increase(aeris_storage_hbase_operation_duration_seconds_bucket{operation=\"Store\",app=\"ingest\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Ingest Storage Latency Median",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(storage_latency_histogram_bucket{app=\"ingest\"}[5m])) by (le))"
      }
     ]
    },
    {
     "title": "Apiserver Publish OK Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "rate(grpc_server_handled_total{grpc_method=\"Publish\", grpc_service=\"RouterV1\", app=\"apiserver\", grpc_code=\"OK\"}[5m]) != 0"
      }
     ]
    },
    {
     "title": "Ingest Publish OK Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 57 },
     "targets": [
      {
       "expr": "rate(grpc_server_handled_total{grpc_method=\"Publish\", grpc_service=\"RouterV1\", app=\"ingest\", grpc_code=\"OK\"}[5m]) != 0"
      }
     ]
    },
    {
     "title": "Apiserver Publish Failed Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 64 },
     "targets": [
      {
       "expr": "rate(grpc_server_handled_total{grpc_method=\"Publish\", grpc_service=\"RouterV1\", app=\"apiserver\", grpc_code!=\"OK\"}[5m]) != 0"
      }
     ]
    },
    {
     "title": "Ingest Publish Failure Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 64 },
     "targets": [
      {
       "expr": "rate(grpc_server_handled_total{grpc_method=\"Publish\", grpc_service=\"RouterV1\", app=\"ingest\", grpc_code!=\"OK\"}[5m]) != 0"
      }
     ]
    }
   ]
  },
  {
   "title": "Aeris Reads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Get request to first response latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 81 },
     "targets": [
      {
       "expr": "sum(increase(aeris_apiserver_get_first_response_latency_seconds_bucket[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Get Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 89 },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{grpc_method=\"Get\", grpc_service=\"RouterV1\"}[5m])) by (grpc_code) != 0"
      }
     ]
    },
    {
     "title": "Get Request Rate by App",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 97 },
     "targets": [
      {
       "expr": "sum(rate(grpc_client_handled_total{grpc_method=\"Get\", grpc_service=\"RouterV1\"}[5m])) by (grpc_code, app) != 0"
      }
     ]
    }
   ]
  }
 ]
}