{
 "title": "case data",
 "time": { "from": "now-14d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DATASOURCE", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Available memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes" }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Load Avg 1m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1" }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU Load 15m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load15" }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Percent disk used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes)"
    }
   ]
  },
  {
   "title": "Disk writes per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_written_bytes_total[2m])"
    }
   ]
  },
  {
   "title": "I/O wait",
   "type": "graph",
   "description": "I/O wait means you can't keep up with the data coming into the cluster - the customer needs to improve their disks or scale the cluster down",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (irate(node_cpu_seconds_total{mode=\"iowait\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "Disk reads per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total[2m])"
    }
   ]
  },
  {
   "title": "Sflow updates",
   "type": "graph",
   "description": "This panel will only have data if the customer is sending Sflow data to their CVP cluster. CVP is limited to 5000 updates per second. Anything over this limit is unsupported.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(clover_ingest_num_notifications_received{type=~\"ipfix|int|greent\"}[5m]))"
    }
   ]
  },
  { "title": "Hbase/Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Hbase maximum sync lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hbase_regionserver_wal_synctime_max"
    }
   ]
  },
  {
   "title": "Hbase 99.9 percentile sync lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hbase_regionserver_wal_synctime_99_9th_percentile"
    }
   ]
  },
  {
   "title": "Hadoop byte reads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(hadoop_datanode_bytesread[2m])"
    }
   ]
  },
  {
   "title": "Kafka LAG",
   "type": "graph",
   "description": "The yellow and red warning ranges in this graph are OPINIONS - if your cluster Kafka lag is this high you should take note, but it may be expected in large scaled clusters",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "abs(max(kafka_log_log_value{topic=\"postDB_v2\", name=\"LogEndOffset\"}) by (partition, topic) - max(offset_consumed{topic=\"postDB_v2\"}) by (topic, partition))"
    }
   ]
  }
 ]
}