{
 "title": "HDFS",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  { "title": "Namenode", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HDFS storage usage reported by namenode",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (hadoop_namenode_used{kubernetes_pod_name!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Under-replicated blocks reported by namenode",
   "type": "timeseries",
   "description": "If this is not 0, you have data AT RISK of loss (it is not lost yet, but not all 3 replicas for it have been written)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Blocks" } },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (hadoop_namenode_underreplicatedblocks{kubernetes_pod_name!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missing blocks reported by namenode",
   "type": "timeseries",
   "description": "If this is greater than 0, you have irreversible data loss\n\nhttps://www.jesseyates.com/2019/03/03/hdfs-blocks-missing-vs-corrupt.html",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Blocks" } },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (hadoop_namenode_missingblocks{kubernetes_pod_name!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Datanode", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Disk used reported by data nodes",
   "type": "timeseries",
   "description": "All 3 nodes should be roughly the same, unless one is replicating, in which case you should see a line going up until the usage matches the peers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (hadoop_datanode_dfsused{kubernetes_pod_name!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Journalnode", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Journalnode transaction lag",
   "type": "timeseries",
   "description": "Number of transactions the journal node is behind the peers by",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (hadoop_journalnode_currentlagtxns{kubernetes_pod_name!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Journalnode not formatted exceptions",
   "type": "timeseries",
   "description": "If this is greater than 0, you have a journalnode in a faulty state",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (hadoop_journalnode_journalnotformattedexceptionnumops{kubernetes_pod_name!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Journal timestamp",
   "type": "timeseries",
   "description": "This should be greater than zero, and increasing over time as HDFS transactions occur.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (hadoop_journalnode_lastjournaltimestamp{kubernetes_pod_name!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}